### ISSUE TITLE
Scope word translation

### ISSUE THREAD

**Issue by Zenfeuer** [You-Dont-Know-JS-ES/Traduccion#21]
Hi, I have a doubt.

What should be the correct translation of **scope** in spanish?

I'm using **alcance**, but it seems to me a little weird. Another proposal could be **ámbito** but I don't know exactly how to translate **scoped** using **ámbito** where **alcance** is more accurate in this case.

Thanks!

**Comment by mballeng91** [comment]
Hi @Zenfeuer. 
As you say, both of them are OK. Let's use **alcance** for that purpose... We could translate **scoped** as **con alcance** so We don´t get in trouble with the use of **ámbito** . Thanks for opening this issue, please let us know if this comment clarifies your doubt.

**Comment by Zenfeuer** [comment]
Thanks @mballeng91 ! Totally clear!
